-- require("plugins.theme")
require("plugins.blink")
require("plugins.git")
require("plugins.mini")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.snip")
require("plugins.noice")
require("plugins.lualine")
require("plugins.theme")
require("plugins.startup")
