cursor #e8e1dd
cursor_text_color #ccc5c1

foreground            #e8e1dd
background            #151311
selection_foreground  #392f24
selection_background  #d4c4b5
url_color             #dac3ac

color0   #151311
color1   #e2497e
color2   #97d66e
color3   #dbae7b
color4   #a97947
color5   #a39587
color6   #dac3ac
color7   #abb2bf
color8   #5c6370
color9   #e05f8f
color10  #a9e086
color11  #e8c297
color12  #e9d0b8
color13  #a56b51
color14  #8e7650
color15  #ffffff
