[settings]
pseudo-transparency = true
screenchange-reload = true

[bar/main]
override-redirect = true
wm-restack        = bspwm
fixed-center      = true
bottom   = false
width    = 100%:-400
height   = 20
offset-y = 10
offset-x = 200
background    = ${colors.bg}
foreground    = ${colors.fg}
font-0        = Hack Nerd Font:size=12;2
separator     = " "
padding-left  = 0
padding-right = 0
modules-left   = rcmen bspwm cpu-label cpu memory-label memory
modules-center = title
modules-right  = tray date volume-label volume powermenu
radius = 0
border-top-size = 2
border-bottom-size = 2
border-size = 0
border-color  = ${colors.bg}

[bar/top]
inherit = bar/main
monitor = HDMI-0

[bar/secondary]
inherit = bar/main
monitor = DP-0
border-size = 2
border-color = ${colors.bg}

;;        ----
;;  colors and fonts
;;        ----

[colors]
fg = ${xrdb:polybar.fg:#e1e2e2}
bg = ${xrdb:polybar.bg:#192222}
uf = ${xrdb:polybar.bg:#4d5761}
ac = ${xrdb:color3:#b3bbc8}
gr = ${xrdb:color8:#884444}
bl = ${xrdb:color7:#884444}
tier0 = ${xrdb:color8:#cacbca}
tier1 = ${xrdb:color3:#cacbca}

;;    ---
;;  modules
;;    ---

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enable-click = true
enable-scroll = true
reverse-scroll = false
fuzzy-match = true
format = <label-state> <label-mode>

ws-icon-0 = 1;
ws-icon-1 = 2;󰖟
ws-icon-2 = 3;
ws-icon-3 = 4;󱁽
ws-icon-4 = 5;󰊖

ws-icon-5 = 6;󰖟
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;󱁽
ws-icon-9 = 10;󰊖

ws-icon-default = 
label-focused = %icon%
label-focused-background = ${colors.ac}
label-focused-foreground = ${colors.bg}
label-focused-padding = 1
label-occupied = %icon%
label-occupied-padding = 1
label-occupied-foreground = ${colors.ac}
label-urgent = %icon%
label-urgent-background = ${colors.gr}
label-urgent-padding = 1
label-empty = %icon%
label-empty-foreground = ${colors.uf}
label-empty-padding = 1

[module/powermenu]
type = custom/text
click-left = powermenu
content = "  "
content-background = ${colors.ac}
content-foreground = ${colors.bg}

[module/rcmen]
type = custom/text
click-left = rofi -show drun
content = " 󱗼 "
content-background = ${colors.ac}
content-foreground = ${colors.bg}

[module/title]
type = internal/xwindow
format = <label>
format-padding = 0
label = %title%
label-maxlen = 35

[module/volume-label]
type = internal/pulseaudio
format-volume = %{A1:pavucontrol:}<ramp-volume>%{A}
format-volume-padding = 1
format-volume-margin = 0
format-volume-background = ${colors.ac}
format-volume-foreground = ${colors.bg}
format-muted = %{A1:pavucontrol:}<label-muted>%{A}
format-muted-padding = 1
format-muted-background = ${colors.ac}
format-muted-foreground = ${colors.bg}
label-muted = 
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰕿
ramp-volume-2 = 󰖀
ramp-volume-3 = 󰖀
ramp-volume-4 = 

[module/volume]
type = internal/pulseaudio
format-volume-margin = 0
format-volume = "<bar-volume> "
format-volume-padding = 0
format-muted = <label-muted>
format-muted-padding = 0
label-volume = %percentage%%
format-muted-prefix =
format-muted-foreground = ${colors.ac}
label-muted = "········"
bar-volume-width = 8
bar-volume-gradient = false
bar-volume-indicator =
bar-volume-fill = ━
bar-volume-foreground-0 = ${colors.ac}
bar-volume-fill-font = 1
bar-volume-empty = ━
bar-volume-empty-foreground = ${colors.gr}
bar-volume-empty-font = 2

[module/kbd-label]
type = custom/text
content = "kbd:"
content-foreground = ${colors.ac}

[module/kbd]
type = internal/xkeyboard
format = <label-layout> <label-indicator>
format-spacing = 1

[module/filesystem-label]
type = internal/fs
mount-0 = /
interval = 10
fixed-values = true
format-mounted-foreground = ${colors.bg}
format-mounted-background = ${colors.ac}
format-mounted = "<ramp-capacity> "
format-mounted-prefix = " "
format-unmounted = " "
format-unmounted-foreground = ${colors.bg}
format-unmounted-background = ${colors.ac}
format-unmounted-prefix = " "
ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "

[module/filesystem]
type = internal/fs
mount-0 = /
interval = 10
fixed-values = true
format-mounted = "<label-mounted>"
format-unmounted = "<label-unmounted>"
label-mounted = %free%
label-unmounted = %mountpoint% is on fire
bar-used-indicator =
bar-used-width = 10
bar-used-fill = |
bar-used-empty = |
bar-used-foreground-0 = ${colors.fg}
bar-used-foreground-1 = ${colors.fg}
bar-used-foreground-2 = ${colors.fg}
bar-used-foreground-3 = ${colors.fg}
bar-used-empty-foreground = ${colors.fg}

[module/date-label]
type = custom/text
content = "  date  "

[module/date]
type = internal/date
interval = 1.0
time = "   %H%M "
time-alt = "   %Y-%m-%d "
format = "<label>"
format-padding = 0
format-background = ${colors.ac}
format-foreground = ${colors.bg}
label = "%time%"

[module/memory-label]
;type = custom/text
;content = "mem:"
;content-foreground = ${colors.ac}
type = internal/memory
interval = 2
format = "<ramp-used> "
format-foreground = ${colors.bg}
format-background = ${colors.ac}
format-prefix = " "
ramp-used-0 = " "
ramp-used-1 = " "
ramp-used-2 = " "
ramp-used-3 = " "

[module/memory]
type = internal/memory
interval = 2
;format = "<ramp-used> <label>"
format = "<label>"
format-prefix =
label = %mb_used%
bar-used-indicator =
bar-used-width = 10
bar-used-fill = |
bar-used-empty = |
bar-used-foreground-0 = ${colors.ac}
bar-used-foreground-1 = ${colors.ac}
bar-used-foreground-2 = ${colors.ac}
bar-used-foreground-3 = ${colors.ac}
bar-used-empty-foreground = ${colors.ac}
ramp-used-0 = 
ramp-used-1 = 
ramp-used-2 = 
ramp-used-3 = 
ramp-used-foreground = ${colors.fg}

;; experimental, doesn't seem to be in xbps' polybar...
[module/tray]
type = internal/tray
format-margin = 8px
tray-spacing = 8px
tray-padding = 2px
tray-size = 16

[module/cpu-label]
type = internal/cpu
interval = 2
format = "   "
format-foreground = ${colors.bg}
format-background = ${colors.ac}

[module/cpu]
type = internal/cpu
interval = 2
format = <label>
label = %percentage%%
